create table movie (id bigint generated by default as identity, category varchar(255) not null, created_date timestamp not null, director varchar(255) not null, title varchar(255) not null, updated_date timestamp not null, shelf_id bigint, primary key (id))
create table shelf (id bigint generated by default as identity, created_date timestamp not null, location varchar(255) not null, updated_date timestamp not null, primary key (id))
alter table movie add constraint FKrt777bw0dy89i2kr6io07j6ow foreign key (shelf_id) references shelf
